[build]
  command = "npm exec vite -- build && node -e \"require('fs').copyFileSync('dist/index.html', 'dist/404.html')\""
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
